# -*- coding: utf-8 -*-
"""Streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j4VKE8SvCjKPd26TC4RQtb9fSIEgqmap
"""

import fitz
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

# Load model once
model = SentenceTransformer('all-MiniLM-L6-v2')

def extract_text_from_pdf(file_path):
    doc = fitz.open(file_path)
    return ''.join([page.get_text() for page in doc])

def chunk_text(text, max_length=500):
    paragraphs = text.split("\n")
    chunks, current_chunk = [], ""
    for para in paragraphs:
        if len(current_chunk) + len(para) < max_length:
            current_chunk += para + " "
        else:
            chunks.append(current_chunk.strip())
            current_chunk = para + " "
    if current_chunk:
        chunks.append(current_chunk.strip())
    return chunks

def get_embeddings(chunks):
    return model.encode(chunks)

# Core logic to answer a question based on a PDF
def answer_question_from_pdf(pdf_path, question):
    text = extract_text_from_pdf(pdf_path)
    chunks = chunk_text(text)
    embeddings = get_embeddings(chunks)
    query_embedding = model.encode([question])
    scores = cosine_similarity([query_embedding[0]], embeddings)[0]
    top_indices = scores.argsort()[-3:][::-1]
    return "\n\n".join([chunks[i] for i in top_indices])

